// Fuente LaTeX de la documentación, en orden de aparición. No calcula el modelo.
module.exports = {
  distancia: String.raw`\begin{aligned}d(u,v)&=\sqrt{(u_x-v_x)^2+(u_y-v_y)^2}\\ \operatorname{clip}(z,l,h)&=\min\{h,\max\{l,z\}\}\end{aligned}`,
  normal: String.raw`\begin{aligned}Z&=\sqrt{-2\ln U_1}\cos(2\pi U_2),\quad U_1,U_2\sim\mathcal U(0,1)\\ X&=m+sZ\end{aligned}`,
  vecinos: String.raw`\begin{aligned}\mathcal N_i&=\{j\ne i:d(u_j,u_i)\le\varepsilon_i\}\\L_i&=\frac{\sum_{j\in\mathcal N_i}(u_j-u_i)}{D_i}\end{aligned}`,
  polos: String.raw`\begin{aligned}b_{ik}&=S\,\mathbf1_{\{d(u_i,p_k)\le\varepsilon_i\}}\,\mathbf1_{\{d(u_i,p_k)\le\rho\}}\\D_i&=1+|\mathcal N_i|+b_{iA}+b_{iB}\\T_i&=\frac{u_i+\sum_{j\in\mathcal N_i}u_j+b_{iA}p_A+b_{iB}p_B}{D_i}\\P_i^{\rm individual}&=\frac{b_{iA}(p_A-u_i)+b_{iB}(p_B-u_i)}{D_i}\\L_i+P_i^{\rm individual}&=T_i-u_i\end{aligned}`,
  calendario: String.raw`\begin{aligned}g&=30+\operatorname{round}\bigl(970(1-f)\bigr)\\D&=20+\operatorname{round}(180c_D)\\I&=\operatorname{clip}\bigl(c_I\mathcal U(0.65,1.35),0,1\bigr)\\t_{\rm primero}&=\operatorname{round}\bigl(g\mathcal U(0,1)\bigr)\\t_{\rm siguiente}&=t+\max\bigl(8,\operatorname{round}(g\mathcal U(0.65,1.35))\bigr)\end{aligned}`,
  contraevento: String.raw`\begin{aligned}\Pr(\text{respuesta}\mid e)&=c_{\rm contra}\\e'&=(1-e_x,1-e_y),\quad t'_0=t_0+3\\D'&=\operatorname{round}(0.65D),\quad I'=0.55I\end{aligned}`,
  eventos: String.raw`\begin{aligned}H&=1+299(1-c_{\rm dec})\\a_e(t)&=\begin{cases}2^{-(t-t_0)/H},&t_0\le t<t_0+D,\\0,&\text{fuera de la ventana}.\end{cases}\\v&=e-u_i,\quad d=\max(\|v\|_2,0.02)\\K&=e^{-d^2/(2\rho_e^2)}\\E_{ie}&=a_eIKv-\mathbf1_{\{\text{bandos distintos}\}}a_eRK\frac{v}{d}\\E_i&=\sum_e E_{ie}\end{aligned}`,
  masa: String.raw`\begin{aligned}c_k&=\frac{1}{n_k}\sum_{i\in k}u_i\\ f_k&=\frac{n_k}{N},\quad\gamma=0.5+1.5c_\gamma,\quad M_k=f_k^\gamma\end{aligned}`,
  grupos: String.raw`\begin{aligned}v_k&=c_k-u_i,\quad d_k=\max(\|v_k\|_2,0.01)\\b&=0.02+0.18\rho_g,\quad K_k=e^{-d_k^2/(2\rho_g^2)}\\C_i&=\sum_k\frac{h_{ik}S_gM_kK_k}{d_k^2+b^2}\,v_k\\h_{ik}&=\begin{cases}c_{\rm auto},&i\in k,\\1,&i\notin k.\end{cases}\end{aligned}`,
  acoplamiento: String.raw`P_i=\begin{cases}P(u_i)+\kappa f_kP(c_k),&i\in k,\\P(u_i),&\text{sin grupo}.\end{cases}`,
  tolerancia: String.raw`\begin{aligned}r_i&=\frac{\|u_i-(0.5,0.5)\|_2}{\sqrt{0.5}}\\\varepsilon_i&=\operatorname{clip}\bigl(\varepsilon_i^0(1-c_r r_i)(1-c_m M_i),0,1\bigr)\\M_i&=0\quad\text{si no hay grupo propio}\end{aligned}`,
  atributos: String.raw`\begin{aligned}\varepsilon_i^0&=\operatorname{clip}(\bar\varepsilon+\bar\varepsilon h Z_i,0,1)\\\mu_i&=c_\mu\\\alpha_i&=c_\alpha\\\lambda_i&=c_\lambda\end{aligned}`,
  jdj: String.raw`\begin{aligned}a_i&=1-\frac{\|u_i-p_A\|_2}{\sqrt2},\quad b_i=1-\frac{\|u_i-p_B\|_2}{\sqrt2}\\P_{ij}&=\max(a_i b_j,b_i a_j)\\\mathrm{JDJ}&=\frac{2}{N^2}\sum_{i=1}^{N}\sum_{j=1}^{N}P_{ij}\end{aligned}`,
  auditor: String.raw`\begin{aligned}m&=\frac1N\sum_i b_i,\quad B=4m(1-m)\\V&=\frac4N\sum_i(b_i-m)^2\\q_t&=\begin{cases}q_{t-1}+1,&\mathrm{JDJ}\ge\theta_J\ \land\ B\ge\theta_B,\\0,&\text{en otro caso}\end{cases}\\\tau&=1+\operatorname{round}(119c_\tau)\\R_i&=\begin{cases}S_c((0.5,0.5)-u_i),&q_t\ge\tau,\\(0,0),&q_t<\tau.\end{cases}\end{aligned}`,
  movimiento: String.raw`\begin{aligned}H_i&=\lambda_i\bigl(u_i(0)-u_i(t)\bigr)\\F_i&=L_i+P_i+E_i+C_i+R_i+H_i\\v_i&=\begin{cases}0.075\mu_iF_i+\xi_i,&\|F_i\|_2>\alpha_i,\\\xi_i,&\|F_i\|_2\le\alpha_i\end{cases}\\\xi_{ix},\xi_{iy}&\sim\mathcal N\bigl(0,(0.012c_{\rm ruido})^2\bigr)\\\widehat v_i&=\begin{cases}v_i,&\|v_i\|_2\le0.05,\\\displaystyle\frac{0.05}{\|v_i\|_2}v_i,&\|v_i\|_2>0.05\end{cases}\\u_i(t+1)&=\operatorname{clip}\bigl(u_i(t)+\widehat v_i,0,1\bigr)\end{aligned}`,
  intensidad: String.raw`I_{\rm visible}(t)=\min\left(1,\sum_e a_e(t)I_e\right)`
};
